title: Reasonable Unreasonableness
author: Rory McLaughlin
description: Adapting myself to the world I aim to adapt to me.
#theme: minima
remote_theme: broccolini/swiss
domain: TXredking.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://TXredking.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /      # place folder name if the site is served in a subfolder

